name: 🏭 Cut Mod Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Semver Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  cut_release:
    name: "Cut Release"
    uses: open-goal/mod-bundling-tools/.github/workflows/mod-bundler.yml@v1
    with:
      semverBump: ${{ inputs.bump }}
      metadataName: "Checkpoint Randomizer"
      metadataDescription: "Warp to a random checkpoint on various triggers (cells, flies, orbs, eco, death)."
      metadataSupportedGames: "jak1"
      metadataAuthors: "zed,barg,MikeGamePro"
      metadataTags: "speedrunning,challenge,gameplay-mod,rng"
      metadataWebsiteUrl: "https://github.com/OpenGOAL-Mods/OG-Randomizer/blob/main/README.md"
      toolingRepo: "OpenGOAL-Mods/OG-Mod-Base"
      gameAssetsDir: "game/assets"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
